### ISSUE TITLE
set up a minimal CLI executable

### ISSUE THREAD

**Issue by benjaminbollen** [eureka-network/substreams-postgres-sync#11]
this minimal CLI should (in later tasks) connect to postgres cursor tables, and makes the request to substreams to continue streaming TracedDatabaseChanges

**Comment by benjaminbollen** [comment]
some quick googling:

- https://github.com/clap-rs/clap is a rich command line parser (used by paradigm/reth, parity/substrate)
- alternatively seahorse as a minimal CLI framework, but seems like no-one is using that

**Comment by benjaminbollen** [comment]
putting this issue back in "todo" because tomorrow morning I'll be away from desk; so if this is a blocker to others, feel free to pick it up

go your own path, or optionally some initial thoughts:
- paritytech/substrate is a good reference for (somewhat heavy, but) thought-through code patterns
- so my approach would be to follow a very minimal version of https://github.com/paritytech/substrate/blob/master/bin/node/cli/src/lib.rs, using clap

an initial workspace commit, you can find here if it's helpful: https://github.com/eureka-network/eureka-sink-rs/compare/develop...20230221-setup-minimal-cli

**Comment by benjaminbollen** [comment]
@vadim-frolov your work continues on https://github.com/eureka-network/eureka-sink-rs/tree/20230221-setup-minimal-cli

**Comment by vadim-frolov** [comment]
PR #38
