### ISSUE TITLE
Improve proto compilation in substreams-sink

### ISSUE THREAD

**Issue by vadim-frolov** [eureka-network/substreams-postgres-sync#12]
- symlink proto sources
- remove compiled rust bindings, run in build.rs

**Comment by vadim-frolov** [comment]
PR #18

**Comment by benjaminbollen** [comment]
I added a review for #18

**Comment by vadim-frolov** [comment]
improved in commit [d9c2957](https://github.com/eureka-network/eureka-sink-rs/commit/d9c2957bf5e7e9ddf76995e0b40f0fb293c32606) Thanks!
