### ISSUE TITLE
Evaluate if there is a direct way to retrieve a db schema table names, as well as its primary key columns

### ISSUE THREAD

**Issue by jorgeantonio21** [eureka-network/substreams-postgres-sync#17]
Currently, we address this question by executing the generic raw SQL queries. Would be preferable to be able to retrieve this information via the db connection, without executing raw queries, if possible.

**Comment by vadim-frolov** [comment]
I'm not sure if it's relevant - https://gitlab.com/teza-ai/sepana-search/ingest/-/blob/main/src/thegraph.rs#L384

**Comment by benjaminbollen** [comment]
Im also still due forming my proper thoughts about it;

I think if we take a step back the objective is to `LoadTables` https://github.com/streamingfast/substreams-sink-postgres/blob/develop/db/db.go#L59
(some golang dependency `JimSmart` goes and gets the primary keys)

- what do we minimally need to load ? is there a Postgres driver that already handles much of this?
- related to this: specifically we want to build a cursors table that is up to date on where we last worked for a given table - can we split this into smaller tasks? we can write bullet points here and make tasks later

**Comment by jorgeantonio21** [comment]
@vadim-frolov this is very relevant and the current approach we use, querying directly from the `information_schema`. 

@benjaminbollen a relevant link regards the `diesel-cli` repo, in which they expose some internal interface for this, which seems to do part of what we want with this issue:

https://github.com/diesel-rs/diesel/blob/master/diesel_cli/src/database.rs#L303

by executing the (equivalent) raw query.

Regarding your first point, following the golang implementation we would want to extract information about existing tables for current schema, as well as its column names and column types. I think this is a sensible think to do, as we need to have our own API to deal effectively with existing tables in the db.

**Comment by vadim-frolov** [comment]
@jorgeantonio21 could you please point me to more details on what we want to achieve in the task?
I would also take a look at the graph DB layout - I happen to have one online. They solve similar tasks, you can browse their tables with DBeaber or another viewer to see if can use similar approaches.

**Comment by benjaminbollen** [comment]
this seems to have been resolved; will close in a few days
