### ISSUE TITLE
Add remaining unit tests for db loader

### ISSUE THREAD

**Issue by jorgeantonio21** [eureka-network/substreams-postgres-sync#19]
I wasn't able to run my tests locally (`cargo test`), with error `error: linking with cc failed: exit code: 1`. After a long time digging, was able to solve this issue by running

`brew install postgresql libpq`

(mac only).

**Comment by benjaminbollen** [comment]
PR has merge conflicts; 

I had similar problem on my machine, but then these instructions should be on a README.md file; it also seems we should not have this dependency. In particular, postgres for us sits contained in a docker at this time. Is it known that Diesel pulls this dependency?

**Comment by benjaminbollen** [comment]
also I setup a simple CI to avoid that things get merged with failing builds / tests
