### ISSUE TITLE
(possible?) replace Git submodules for retrieving proto files with explicit cargo.toml dependency instead

### ISSUE THREAD

**Issue by benjaminbollen** [eureka-network/substreams-postgres-sync#28]

**Comment by benjaminbollen** [comment]
for now added `git submodule init && git submodule update &&` to the `rust.yml` CI definition, but this should not be how we build the repository

**Comment by benjaminbollen** [comment]
started on a draft to instead `curl` the files during `build.rs`

**Comment by vadim-frolov** [comment]
suggested PR #64

**Comment by benjaminbollen** [comment]
superceded by #64
