### ISSUE TITLE
fix typo in type of clap config

### ISSUE THREAD

**Issue by benjaminbollen** [eureka-network/substreams-postgres-sync#41]
`start_block` should be `u64`?

https://github.com/eureka-network/eureka-sink-rs/pull/38#discussion_r1119936565

**Comment by vadim-frolov** [comment]
[substreams.proto](https://github.com/streamingfast/substreams/blob/develop/proto/sf/substreams/v1/substreams.proto):

message Request {
  int64 start_block_num = 1;
  string start_cursor = 2;
  uint64 stop_block_num = 3;
...

**Comment by benjaminbollen** [comment]
alternatively we could leave this open to inquire why this choice; we can put a //todo in the code later
