### ISSUE TITLE
Implement type `Cursor` interface

### ISSUE THREAD

**Issue by jorgeantonio21** [eureka-network/substreams-postgres-sync#44]
The interace should follow along: 

```rs
pub struct Cursor {
  cursor: String,
  block: BlockRef
}

impl Cursor {
  pub fn new(cursor: String, block: BlockRef) -> Self {}
  pub fn new_blank_cursor() -> Self {}
  pub fn is_blank(&self) -> bool {}
  pub fn is_equal_to(&self, other: &Self) -> bool {}
  pub fn to_string(&self) -> String {}
}
```

**Comment by jorgeantonio21** [comment]
One can find more details in the GoLang implementation: 

https://github.com/streamingfast/substreams-sink/blob/develop/types.go

**Comment by vadim-frolov** [comment]
PR #46

**Comment by benjaminbollen** [comment]
`BlockRef` from `bstream` (aka Firehose) includes an `id` (blockhash); and a blocknumber;

in the `Clock` from Substreams `BlockScopedData` we get the `id`, `block number` and the block `timestamp`; as we're in a higher level of the stack, it might be valuable enough to be aware of the timestamp in our cursor table (as it would not be big, and gives some reference to current time)

**Comment by benjaminbollen** [comment]
vadim:

>from firehose changelog:
>> The blocks that do not make it in the merged-blocks (forked out because of a re-org) are uploaded to another store (common-forked-blocks-store-url) and kept there for a while (to allow resolving cursors)

>> The Firehose cursor points to a specific position in the stream of events emitted by ForkDB and the blockchain itself. The ForkDB cursor contains information that is required to reconstruct an equivalent forked or canonical instance. Consumer requests for historical blocks are fetched from persistent Firehose storage. The historical blocks are passed inside a ForkDB and sent with a cursor uniquely identifying the block and its position in the blockchain.

ben:

> Ok, so I understand:
>we treat Cursor as a new data type, a string known to be resolved by Firehose/Substreams to retrieve or reconstruct past historical state, and for our purposes we just store it at this time
