### ISSUE TITLE
Add support for SF endpoints

### ISSUE THREAD

**Issue by vadim-frolov** [eureka-network/substreams-postgres-sync#77]
https://substreams.streamingfast.io/reference-and-specs/chains-and-endpoints

**Comment by benjaminbollen** [comment]
(moved this to WitnessDB, because we would mostly need it for ingesting offchain state)

**Comment by vadim-frolov** [comment]
PR #77

**Comment by benjaminbollen** [comment]
PR #83 (not 77)
