### ISSUE TITLE
setup simple way to get access to firehose

### ISSUE THREAD

**Issue by benjaminbollen** [eureka-network/substreams-postgres-sync#8]
We can initially leverage the firehose API endpoint StreamingFast provides to Ethereum mainnet; this will help for a simplified integrated test scripts

**Comment by benjaminbollen** [comment]
PR #13

**Comment by vadim-frolov** [comment]
started reviewing and commenting in the PR

**Comment by benjaminbollen** [comment]
continued in PR; I would still prefer a `.env` file approach to separate out private variables from committed files
