### ISSUE TITLE
Initial crate for substream-sink

### ISSUE THREAD

**Issue by benjaminbollen** [eureka-network/substreams-postgres-sync#9]
Create initial crate for substream-sink, such that we can use this dependency to call substreams from `eureka-sink-rs`

first PR completed by #4 and #7

**Comment by benjaminbollen** [comment]
@vadim-frolov maybe make a new issue for the question on whether we can depend on, rather than copy, the protobuf files from Substreams; then this one can go to completion

**Comment by vadim-frolov** [comment]
protobuf to be refactored in #12
