### ISSUE TITLE
test the event commitment trie on substreams with real data

### ISSUE THREAD

**Issue by benjaminbollen** [eureka-network/substreams-postgres-sync#93]
in wasm32 handler:
- get `pb::Block` as argument
- use `BlockCommitment`
- write out recordChanges of `EncodedLogs` (this is mostly for our own debugging as we build out circuits)

**Comment by benjaminbollen** [comment]
- [x] complete sync of events and encoded logs into postgres
- [x] run it on block

**Comment by jorgeantonio21** [comment]
Resolved in #102
